# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/', verbose_name='Ссылка картинки'),
        ),
    ]
