# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-27 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_articles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/%Y/%m/%d/', verbose_name='Ссылка картинки'),
        ),
    ]
