# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('page', '0005_articles_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_top', models.CharField(max_length=120)),
                ('body_top', models.TextField()),
                ('date_top', models.DateTimeField()),
                ('author_top', models.CharField(blank=True, max_length=100, null=True, verbose_name='Автор')),
                ('image_top', models.ImageField(blank=True, help_text='150x150px', upload_to='images/%Y/%m/%d/', verbose_name='Ссылка картинки')),
                ('tags_top', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
