# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-08 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_toparticles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toparticles',
            name='author_top',
        ),
        migrations.RemoveField(
            model_name='toparticles',
            name='date_top',
        ),
        migrations.RemoveField(
            model_name='toparticles',
            name='image_top',
        ),
        migrations.RemoveField(
            model_name='toparticles',
            name='tags_top',
        ),
        migrations.AlterField(
            model_name='toparticles',
            name='title_top',
            field=models.CharField(max_length=100),
        ),
    ]
