# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_toparticles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='toparticles',
            name='tags_top',
        ),
        migrations.DeleteModel(
            name='TopArticles',
        ),
    ]
