# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 18:33
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20180711_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top',
        ),
        migrations.AlterField(
            model_name='genre',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='page.Genre', verbose_name='Родительский класс'),
        ),
    ]
